<?php
/**
 * @copyright Copyright (c) Misha Medzhytov <mdg12v@gmail.com>, All rights reserved.
 */

// @codingStandardsIgnoreFile
/** @var $block \Mdg\InvoicePayment\Block\Info\Invoice */
/** @var Magento\Sales\Model\Order $order */
$order = $block->getInfo()->getOrder();

/** @var \Mdg\InvoicePayment\Model\Payment\Invoice $methodInstance */
$methodInstance = $order->getPayment()->getMethodInstance();
?>
<div class="invoice-payment-info">
    <?php if ($instructions = $methodInstance->getConfigData('invoice_instructions')): ?>
    <p><?= $instructions ?></p>
    <?php endif ?>
    <p><a href="<?= $block->getUrl('print/sales/order', ['order_id' => $order->getIncrementId()]) ?>">
            <img style="vertical-align: bottom" src='<?php echo $block->getViewFileUrl('Mdg_InvoicePayment::images/icon-pdf.png'); ?>' /> <?= __('Download invoice PDF') ?>
        </a>
    </p>
</div>